version: "3.9"

services:
  hr-pipeline:
    build:
      context: .
      dockerfile: dockerfile.dwh
    image: acrgrupp11id015.azurecr.io/hr-pipeline:latest # 채ndra h채r till din ACR
    ports:
      - "3000:3000"

  dashboard:
    build:
      context: .
      dockerfile: dockerfile.dashboard
    image: acrgrupp11id015.azurecr.io/dashboard:latest # 채ndra h채r till din ACR
    ports:
      - "8501:8501" 