version: "3.9"

services:
  dwh_pipeline:
    build:
      context: .
      dockerfile: dockerfile.dwh
    ports:
      - "3000:3000"
    image: acrgrupp1db0rgc.azurecr.io/hr-pipeline:latest #ändra sen till din egna acrgrupp1xxxxxx

  dashboard:
    build:
      context: .
      dockerfile: dockerfile.dashboard
    ports:
      - "8501:8501"
    image: acrgrupp1db0rgc.azurecr.io/dashboard:latest #ändra sen till din egna acrgrupp1xxxxxx