version: "3.9"

services:
  dwh_pipeline:
    build:
      context: .
      dockerfile: dockerfile.dwh
    ports:
      - "3000:3000"
    image: acrgrupp13o5rc6.azurecr.io/hr-pipeline:latest

  dashboard:
    build:
      context: .
      dockerfile: dockerfile.dashboard
    ports:
      - "8501:8501"
    image: acrgrupp1xrwzyj.azurecr.io/dashboard:latest