FROM python:3.11-slim

ENV DUCKDB_PATH=/duck_pond/job_ads.duckdb

WORKDIR /app/dashboard

COPY dashboard/ /app/dashboard/

RUN pip install streamlit duckdb pandas

CMD ["streamlit", "run", "run_dashboard.py", "--server.port=8501", "--server.address=0.0.0.0"]