sources:
  - name: job_ads
    schema: staging
    tables:
      - name: stg_ads
        identifier: job_ads
        meta: # This metadata specifies the corresponding Dagster asset for this dbt source.
          dagster:
            asset_key: ['job_ads']